### ISSUE TITLE
chrome extension 

### ISSUE THREAD

**Issue by eghan** [serenadeai/serenade#18]
## System Information

macOS 12.6

**Serenade Version:** e.g., v2.0.1
v2.0.1
**OS and Version:** e.g., macOS 12.4
12.6
**Application:** e.g., VS Code
vs code
## Issue Description
chrome extension dialogue has no close option
## How to Reproduce
it pops up and won't leave, periodically

**Comment by eghan** [comment]
<img width="288" alt="Screen Shot 2022-12-23 at 12 57 41 PM" src="https://user-images.githubusercontent.com/23048746/209405009-4bd24811-b346-4c5d-aa53-fc95a57f167d.png">

**Comment by eghan** [comment]
no dismiss, recurring, pins to top of screen, requires focus and minimize to remove temporarily.

**Comment by tmacwill** [comment]
thanks for the report! to disable these suggestions, you can add the below to `~/.serenade/settings.json`:

```
"disable_suggestions": true
```
