### ISSUE TITLE
Block auto Update from v 2.0.0 until bug in 2.0.2 GUI is resolved?

### ISSUE THREAD

**Issue by mark-pippin** [serenadeai/serenade#19]
v 2.0.0 works fine on my system. It constantly auto updates to v 2.0.2 that has a bug tracked on another issue pending triage. 

Is there any way to BLOCK the constant auto update to the buggy version? I am quite tired of re-installing.

**Comment by tmacwill** [comment]
hi there! in order to block Serenade from auto-updating, you can add the following to your `~/.serenade/settings.json` file:

```
"disable_auto_update": true
```
